# Generated by Django 3.0.6 on 2020-05-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtlcustomer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='teste',
            field=models.CharField(default='Teste de campo', max_length=255),
        ),
    ]
