# Generated by Django 3.0.5 on 2020-05-12 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dtlcustomer', '0002_customer_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='teste',
        ),
    ]
