# Generated by Django 3.1 on 2020-04-25 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtlperson', '0002_address_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dtlperson.address'),
        ),
        migrations.AddField(
            model_name='person',
            name='register_date',
            field=models.DateTimeField(auto_now=True, verbose_name='register date'),
        ),
    ]
