# Generated by Django 3.1 on 2020-04-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtlperson', '0004_auto_20200425_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.IntegerField(),
        ),
    ]
