# Generated by Django 3.1 on 2020-04-25 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtlperson', '0005_auto_20200425_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dtlperson.person'),
        ),
    ]
