# Generated by Django 3.1 on 2020-04-25 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dtlperson', '0007_auto_20200425_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Cliente'},
        ),
    ]
