# Generated by Django 3.1 on 2020-04-26 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtlperson', '0008_auto_20200425_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dtlperson.person', verbose_name='Pessoa'),
        ),
    ]
