# Generated by Django 3.1 on 2020-04-26 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dtlperson', '0009_auto_20200425_2224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dtlperson.person',),
        ),
    ]
