# Generated by Django 3.1 on 2020-04-26 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dtlperson', '0010_auto_20200425_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dtlperson.person',),
        ),
    ]
