# Generated by Django 3.1 on 2020-04-26 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtlperson', '0017_auto_20200426_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='E-mail')),
                ('site', models.CharField(max_length=255, null=True, verbose_name='Site')),
                ('phone', models.CharField(max_length=255, null=True, verbose_name='Telefone')),
                ('cell', models.CharField(max_length=255, null=True, verbose_name='Celular')),
                ('person', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='dtlperson.person')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=255, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='address',
            name='complement',
            field=models.CharField(max_length=255, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=255, null=True, verbose_name='Pais'),
        ),
        migrations.AddField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=255, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='address',
            name='quarter',
            field=models.CharField(max_length=255, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=255, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='person',
            name='document',
            field=models.CharField(max_length=255, null=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AddField(
            model_name='person',
            name='register_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.IntegerField(null=True, verbose_name='Número'),
        ),
    ]
