# Generated by Django 3.1 on 2020-04-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtlperson', '0018_auto_20200426_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
    ]
