# Generated by Django 3.0.6 on 2020-05-10 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dtlperson', '0019_auto_20200426_0130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
